// Mocks generated by Mockito 5.4.6 from annotations
// in midi_visualizer_studio/test/features/home/ui/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:midi_visualizer_studio/data/models/project.dart' as _i2;
import 'package:midi_visualizer_studio/data/repositories/project_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProject_0 extends _i1.SmartFake implements _i2.Project {
  _FakeProject_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i3.ProjectRepository {
  MockProjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveProjectInternal(_i2.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#saveProjectInternal, [project]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> exportProject(_i2.Project? project, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#exportProject, [project, path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> importProject(String? sourcePath) =>
      (super.noSuchMethod(
            Invocation.method(#importProject, [sourcePath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Project> loadProject(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#loadProject, [path]),
            returnValue: _i4.Future<_i2.Project>.value(
              _FakeProject_0(this, Invocation.method(#loadProject, [path])),
            ),
          )
          as _i4.Future<_i2.Project>);

  @override
  _i4.Future<List<_i2.Project>> getProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getProjects, []),
            returnValue: _i4.Future<List<_i2.Project>>.value(<_i2.Project>[]),
          )
          as _i4.Future<List<_i2.Project>>);

  @override
  _i4.Future<void> deleteProject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProject, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.Project createProject({required int? rows, required int? cols}) =>
      (super.noSuchMethod(
            Invocation.method(#createProject, [], {#rows: rows, #cols: cols}),
            returnValue: _FakeProject_0(
              this,
              Invocation.method(#createProject, [], {#rows: rows, #cols: cols}),
            ),
          )
          as _i2.Project);

  @override
  _i2.Project createEmptyProject() =>
      (super.noSuchMethod(
            Invocation.method(#createEmptyProject, []),
            returnValue: _FakeProject_0(
              this,
              Invocation.method(#createEmptyProject, []),
            ),
          )
          as _i2.Project);
}
